### ISSUE TITLE
Questions on browser usage.

### ISSUE THREAD

**Issue by 3cp** [parcel-bundler/source-map#108]
Hi, I noticed in order to use `@parcel/source-map` in browser environment, I need to wait for `init` before usage.

```js
import { default as SourceMap, init } from '@parcel/source-map';

await init; // init wasm binary
// Then start using SourceMap.
```

Two questions here:
1. the `init` is not provided by the typings in `index.d.ts`. That will trouble TypeScript users.
2. Should not this lib do waiting on `init` without asking user to do it?
  * It's possible to use top level await on `init` in `src/wasm.js`.
  * In Nodejs environment, `init` is exported but is effectively a noop. Let the lib waits on `init` (and also remove `init` from export) can normalise the usage in Nodejs and browser.

**Comment by mischnic** [comment]
Ideally, top level await would be used internally and we wouldn't have to export `init`. But this library is used in environments where TLA isn't available. 

> the init is not provided by the typings in index.d.ts. That will trouble TypeScript users.

It should definitely be added.

**Comment by 3cp** [comment]
Understood. TLA is for Nodejs v14.8.0+. Since v12 is EOL now, hopefully TLA can be used in near future when Nodejs v12 support is removed from parcel.

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/source-map/commit/d84c22d462e441ac2d6ee0d43ce52e5c22a6f810
