### ISSUE TITLE
missing linux arm64 build target in parcel_sourcemap_node

### ISSUE THREAD

**Issue by jonka-blip** [parcel-bundler/source-map#70]
there are several build targets in parcel_sourcemap_node/artefacts. For Apple M1 chips there is index.darwin-arm64.node. 

sadly, when running docker/linux system on a M1 chip I get a `Error: Cannot find module './artifacts/index.linux-arm64-musl.node'` 

Is it possible to add this build target?

**Comment by jonka-blip** [comment]
this happened on `parcel@2.0.0-nightly.731`, so the referenced source-map version is `2.0.0-rc.4`. 

I managed to compile a static lib with rust and successfully injected that into `/artefacts` at docker runtime by the way.

**Comment by mischnic** [comment]
All platforms supported by Parcel itself
https://github.com/parcel-bundler/parcel/blob/v2/.github/workflows/tag-release.yml
https://unpkg.com/browse/@parcel/hash@2.0.0-nightly.2357/

should definitely also be covered here

**Comment by DeMoorJasper** [comment]
Yeah, I skipped some targets to get this out the door quicker if anyone wants to help with this feel free to look into this. It's mainly changing the  workflow scripts https://github.com/parcel-bundler/source-map/tree/master/.github/workflows

There might also be some minor tweaks in other build scripts

**Comment by janfilips** [comment]
I'm dealing with this error -

`application_1  | $ parcel serve ./index.js --no-hmr --target browser --dist-dir /app/dashboard/static/dashboard --public-url /static/dashboard --log-level info &
application_1  | Error: Error loading shared library /app/frontend/node_modules/@parcel/source-map/parcel_sourcemap_node/artifacts/index.linux-arm64-musl.node: Exec format error
application_1  |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1150:18)
application_1  |     at Module.load (node:internal/modules/cjs/loader:971:32)
application_1  |     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
application_1  |     at Module.require (node:internal/modules/cjs/loader:995:19)
application_1  |     at require (/app/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
application_1  |     at Object.<anonymous> (/app/frontend/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js:15:18)
application_1  |     at Module._compile (/app/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
application_1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
application_1  |     at Module.load (node:internal/modules/cjs/loader:971:32)
application_1  |     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
application_1  |   code: 'ERR_DLOPEN_FAILED'
application_1  | }
`

Using parcel@2.0.0-beta.3.1

Any help or pointing me in the right direction will be highly appreciated.

**Comment by janfilips** [comment]
I get this error using parcel@2.0.0-nightly.731 -

`Error: Error loading shared library /app/frontend/node_modules/@parcel/source-map/parcel_sourcemap_node/artifacts/index.linux-arm64-musl.node: Exec format error
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1150:18)
at Module.load (node:internal/modules/cjs/loader:971:32)
at Function.Module._load (node:internal/modules/cjs/loader:812:14)
at Module.require (node:internal/modules/cjs/loader:995:19)
at require (/app/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
at Object.<anonymous> (/app/frontend/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js:15:18)
at Module._compile (/app/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
at Module.load (node:internal/modules/cjs/loader:971:32)
at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
|   code: 'ERR_DLOPEN_FAILED'
| }
`

Any help or pointing me in the right direction will be highly appreciated.

**Comment by Pitbi** [comment]
Hello,

I have similar issue when running docker/linux system on a M1 chip too. I get:
`Error: Cannot find module './artifacts/index.linux-arm64-gnu.node'`

Parcel version: `2.0.0-rc.0`

**Comment by janfilips** [comment]
Same here with parcel version: parcel@2.0.0-nightly.731 on M1 chip..
