### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/source-map#71]
on macOS 10.13.6:
```
Symbol not found: ____chkstk_darwin
  Referenced from: /@parcel/source-map/parcel_sourcemap_node/artifacts/index.darwin-x64.node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by mischnic** [comment]
Binary built with `MACOSX_DEPLOYMENT_TARGET=10.9 yarn build:node-release`:

[index.darwin-x64.node.zip](https://github.com/parcel-bundler/source-map/files/6718793/index.darwin-x64.node.zip)

**Comment by danieltroger** [comment]
Very cool, seems to work. I vote for use in CI
