### ISSUE TITLE
support node >= 12

### ISSUE THREAD

**Issue by evcohen** [parcel-bundler/source-map#83]
hi! the main parcel package.json supports >= 12 but this one is:

```
  "engines": {
    "node": "^12.18.3 || >=14"
  },
```

unfortunately, at work we're on 12.18.2 so i'm unable to install parcel at all. should this align with the main parcel package?

**Comment by DeMoorJasper** [comment]
There's a bug in older versions of node 12 which cause various native modules to fail, so I'd recommend upgrading as we can't reliably support that version

**Comment by evcohen** [comment]
would love to upgrade. there's still the issue that the min engine for the parcel main package is `>= 12.0.0` (https://github.com/parcel-bundler/parcel/blob/v2/package.json#L60) and this one is different than that. this leaves everything in between v12.0.0 and v12.18.3 unusable.

should we consider raising the min version on the main parcel package?

**Comment by DeMoorJasper** [comment]
Yes, feel free to open an issue in the main repository about that
