### ISSUE TITLE
release v2.0.1 on npm and cargo

### ISSUE THREAD

**Issue by h-a-n-a** [parcel-bundler/source-map#89]
Would you mind releasing the latest version on npm and cargo? Thank you again for your great work :)

**Comment by devongovett** [comment]
Hmm looks like it was forgotten. I just pressed the button.

**Comment by devongovett** [comment]
Hmm it failed. Looks like a compilation error. cc @DeMoorJasper 

https://github.com/parcel-bundler/source-map/runs/4849258463?check_suite_focus=true

**Comment by devongovett** [comment]
I think the core crate probably should not depend on napi anyway. 🤔

**Comment by devongovett** [comment]
Fixed that issue in c0e877fb23b6c351ecc452cdec209b46fd496db0.
